<?php

/**
 * @author Hone Watson
 * @email code@hone.be
 * @copyright  Copyright (c) 2013 Hone Watson
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
class ProtectedReflectionFactoryTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Apiframework\Test\ProtectedReflectionFactory
     */
    protected $factory;

    protected function setUp()
    {

        $this->factory = new Apiframework\Test\ProtectedReflectionFactory();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testBuild()
    {

        $ProtectedReflection = $this->factory->build(new Robot);
        $this->assertInstanceOf('Apiframework\Test\ProtectedReflection', $ProtectedReflection);
        return $ProtectedReflection;
    }

    /**
     * @param $ProtectedReflection
     * @depends testBuild
     */
    public function testProperties($ProtectedReflection)
    {

        $test = $this->factory->build($ProtectedReflection);
        $this->assertInstanceOf("Robot", $test->getProperty("TestClass"));
        $this->assertInstanceOf("ReflectionClass", $test->getProperty("ReflectionClass"));
    }

}
 